/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DuplicateGroup {
  'winner' : KeywordEntry,
  'duplicates' : Array<KeywordEntry>,
  'keyword' : string,
}
export interface KeywordEntry {
  'id' : bigint,
  'frequency' : bigint,
  'keyword' : string,
}
export interface _SERVICE {
  'addEntries' : ActorMethod<[Array<[string, bigint]>], Array<bigint>>,
  'addEntry' : ActorMethod<[string, bigint], bigint>,
  'analyzeDuplicates' : ActorMethod<[], Array<DuplicateGroup>>,
  'cleanDuplicates' : ActorMethod<[], undefined>,
  'clearAll' : ActorMethod<[], undefined>,
  'deleteEntry' : ActorMethod<[bigint], undefined>,
  'getAllEntries' : ActorMethod<[], Array<KeywordEntry>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];