/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const KeywordEntry = IDL.Record({
  'id' : IDL.Nat,
  'frequency' : IDL.Nat,
  'keyword' : IDL.Text,
});
export const DuplicateGroup = IDL.Record({
  'winner' : KeywordEntry,
  'duplicates' : IDL.Vec(KeywordEntry),
  'keyword' : IDL.Text,
});

export const idlService = IDL.Service({
  'addEntries' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'addEntry' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'analyzeDuplicates' : IDL.Func([], [IDL.Vec(DuplicateGroup)], ['query']),
  'cleanDuplicates' : IDL.Func([], [], []),
  'clearAll' : IDL.Func([], [], []),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(KeywordEntry)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const KeywordEntry = IDL.Record({
    'id' : IDL.Nat,
    'frequency' : IDL.Nat,
    'keyword' : IDL.Text,
  });
  const DuplicateGroup = IDL.Record({
    'winner' : KeywordEntry,
    'duplicates' : IDL.Vec(KeywordEntry),
    'keyword' : IDL.Text,
  });
  
  return IDL.Service({
    'addEntries' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'addEntry' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'analyzeDuplicates' : IDL.Func([], [IDL.Vec(DuplicateGroup)], ['query']),
    'cleanDuplicates' : IDL.Func([], [], []),
    'clearAll' : IDL.Func([], [], []),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(KeywordEntry)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };